version: '1'
services:
  node:
    image: node:latest
    container_name: myApp
    command: sh -c "npm install && npm run start:dev"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      MYSQL_DATABASE: "peck"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_HOST: "mysql"
      MYSQL_PORT: 3306
    depends_on:
      - mysql
  mysql:
    image: 'mysql:8.0'
    container_name: myDb
    environment:
        MYSQL_DATABASE: 'peck'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: {} 