version: '1'
services:
  node:
    image: node:latest
    container_name: myApp
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      MYSQL_DATABASE: 'peck'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_HOST: 'mysql'
      MYSQL_PORT: 3306
    depends_on:
      - mysql
    command: sh -c 'npm install && npm run start:dev'
  mysql:
    image: 'mysql:8.0'
    container_name: myDb
    environment:
        MYSQL_DATABASE: 'peck'
        MYSQL_ROOT_USER: 'root'
        MYSQL_ROOT_PASSWORD: 'password'
        MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: {} 